export let ADD_EDGE = 'ADD_EDGE';
export let ADD_VERTEX = 'ADD_VERTEX';
export let UPDATE_EDGE = 'UPDATE_EDGE';
export let UPDATE_VERTEX = 'UPDATE_VERTEX';
export let UPDATE_CURRENT_OPERATIONS = 'UPDATE_CURRENT_OPERATIONS';